name: Test

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: node
        run: echo "##[set-output name=versoin;]$(cat .nvmrc)"
        id: node
      - uses: actions/setup-node@v5
        with:
          node-version: "${{ steps.node.outputs.version }}"
      - name: Run tests
        run: |
          npm ci
          npm run lint
          npm run test:type
      - name: Run e2e tests
        run: |
          echo "..."
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: diff_output
          path: test/e2e/__image_snapshots__/__diff_output__
